# Generated by Django 5.2.18 on 2026-10-09 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('POSTIT_MAX_IMAGE_SIZE_BYTES', 'Maximum image size'), ('POSTIT_MAX_POST_IMAGES', 'Maximum post images'), ('POSTIT_MAX_PROFILE_MEDIA', 'Maximum profile media'), ('POSTIT_MAX_POST_LENGTH', 'Maximum post length'), ('POSTIT_MAX_COMMENT_LENGTH', 'Maximum comment length')], max_length=40, unique=True)),
                ('value', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_platform_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
