# Generated by Django 5.2.18 on 2026-10-09 18:03

import common.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    Profile = apps.get_model('profiles', 'Profile')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    database = schema_editor.connection.alias
    profiles = (
        Profile(user_id=user_id)
        for user_id in User.objects.using(database).values_list("pk", flat=True)
    )
    Profile.objects.using(database).bulk_create(
        profiles,
        batch_size=500,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to=profiles.models.profile_image_upload_to, validators=[common.validators.validate_uploaded_image])),
                ('cover_image', models.ImageField(blank=True, upload_to=profiles.models.profile_image_upload_to, validators=[common.validators.validate_uploaded_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profiles.models.profile_image_upload_to, validators=[common.validators.validate_uploaded_image])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profiles.profile')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.RunPython(
            create_profiles_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
